package br.com.economicdrive.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import br.com.economicdrive.constantes.Constantes;

/**
 * Created by Flavio on 12/09/2017.
 */

public class ModeloDAO extends SQLiteOpenHelper{

    public ModeloDAO(Context context) {
        super(context, "EconomicDrive.sqlite", null, Constantes.DATABASE_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        String sql = "CREATE TABLE modelo(" +
                "id INTEGER PRIMARY KEY AUTOINCREMENT," +
                "nome VARCHAR(100), "+
                "idMarca INTEGER)";
        db.execSQL(sql);
        insertData(db);
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        String sql = "DROP TABLE IF EXISTS modelo";
        db.execSQL(sql);
        onCreate(db);
    }

    private void insertData(SQLiteDatabase db) {
        //MODELOS
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Marruá',1");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'DB9 Volante',2");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'DBS Coupe',2");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'DBS Volante',2");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Rapide',2");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'V12 Vantage Coupe',2");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'V8 Vantage Coupe',2");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'V8 Vantage Roadster',2");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Virage',2");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'A1',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'A3',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'A3 Sedan',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'A4 Avant',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'A4 Sedã',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'A5',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'A7',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'A8',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Q3',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Q5',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Q7',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'R8',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'R8 GT',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'RS 3 Sportback ',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'RS 5',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'RS6 Avant',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'TT Coupé',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'TT Roadster',3");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Continental Flying Spur',4");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Continental Supersports Coupé',4");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Série 1',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Série 1 Cabrio',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Série 1 Coupé',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Série 1 M',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Série 3 Cabrio',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Série 3 M3 Coupé',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Série 3 M3 Sedã',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Série 3 Sedã',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Série 5 Gran Turismo',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Série 5 Sedã',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Série 7 Sedã',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'X1',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'X3',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'X5',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'X6',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Z4 Roadster',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'i3',5");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Chana Cargo',6");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Chana Family',6");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Chana Utility',6");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Celer Hatch',7");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Celer Sedan',7");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cielo Hatch',7");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cielo Sedan',7");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Face',7");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'QQ',7");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'S-18',7");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Tiggo',7");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Agile',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Astra Hatch',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Astra Sedan',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Blazer',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Camaro',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Captiva',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Celta',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classic',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cobalt',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Corsa Hatch',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Corsa Sedã',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cruze ',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cruze Sport6',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Malibu',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Meriva',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Montana',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Omega',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Onix',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Prisma',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'S10',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Sonic',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Spin',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Tracker ',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Trailblazer',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Vectra',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Vectra GT',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Zafira',8");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '300C',9");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Town & Country ',9");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Aircross',10");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'C3',10");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'C3 Picasso',10");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'C4',10");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'C4 Lounge',10");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'C4 Pallas',10");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'C4 Picasso',10");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'C5',10");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'C5 Tourer',10");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'DS3',10");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'DS5',10");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Jumper',10");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Xsara Picasso',10");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Journey ',11");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Effa Hafei Furgão ',12");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Effa Hafei Picape Baú',12");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Effa Hafei Picape Cabine Dupla ',12");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Effa Hafei Picape Cabine Simples ',12");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Effa Hafei Van',12");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Effa M100',12");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '458',13");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'California',13");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'F599 GTO',13");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '500',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Bravo',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Doblô',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Doblô Cargo',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Ducato',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Fiorino',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Freemont',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Grand Siena',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Idea',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Linea',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Mille',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Palio',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Palio Adventure',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Palio Weekend',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Punto',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Siena EL',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Strada',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Uno',14");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Courier',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'EcoSport',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Edge',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'F-250',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Fiesta Rocam Hatch',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Fiesta Rocam Sedan',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Focus Hatch',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Focus Sedan',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Fusion ',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Ka',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Ka+',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'New Fiesta',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'New Fiesta Hatch',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Ranger',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Transit',15");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'EC7',16");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Pick-up',17");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Towner Furgão',17");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Towner Jr',17");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Towner Passageiro',17");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Accord',18");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'CR-V',18");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'City',18");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Civic',18");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Civic Si',18");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Fit',18");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Azera',19");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Equus',19");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'HB20',19");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'HB20S',19");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'HB20X',19");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'HR',19");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Santa Fe',19");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Sonata',19");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Tucson',19");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Veloster',19");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Veracruz',19");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'i30',19");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'i30 CW',19");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'iX35',19");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Daily 35S14',20");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'J2',21");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'J3',21");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'J3 Turin',21");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'J5',21");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'J6',21");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'F-Type Coup?',22");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'XF',22");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'XJ Supersport',22");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'XKR',22");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cherokee',23");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Grand Cherokee',23");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Wrangler',23");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Topic Furgão',24");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Topic Passageiro',24");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Bongo',25");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cadenza',25");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Carens',25");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Carnival',25");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cerato',25");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Mohave',25");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Optima',25");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Picanto',25");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Sorento',25");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Soul',25");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Sportage',25");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Gallardo LP 560 - 4',26");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Gallardo LP 560 - 4 Spyder ',26");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Defender',27");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Discovery 4',27");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Freelander 2',27");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Range Rover Evoque',27");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Range Rover Sport',27");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Range Rover Vogue',27");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '320',28");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '530',28");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '620',28");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'X60',28");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Mahindra Picape',29");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Mahindra SUV',29");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Ghibli',30");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Gran Cabrio',30");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Gran Turismo',30");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Quattroporte',30");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'CLA',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe A',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe B',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe C',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe C 250 Turbo Sport ',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe C 63 AMG Touring',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe CL',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe CLS 63 AMG',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe E',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe G',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe GL',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe GLK',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe M',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe S',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe S 400 Hybrid',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe SLK',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Classe SLS AMG',31");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'MG 550',32");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'MG 6',32");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cooper',33");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cooper Cabrio ',33");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cooper Countryman ',33");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cooper S Clubman-Hampton',33");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'One',33");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'ASX',34");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'L200 Outdoor',34");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'L200 Savana',34");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'L200 Triton',34");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Lancer Evolution X',34");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Outlander',34");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Pajero Dakar',34");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Pajero Full ',34");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Pajero Sport',34");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Pajero TR4',34");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Frontier',35");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Grand Livina',35");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Livina',35");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'March',35");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Sentra',35");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Tiida Hatch',35");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Tiida Sedan',35");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Versa',35");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '207',36");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '207 SW',36");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '207 Sedan',36");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '208',36");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '3008',36");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '307',36");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '308',36");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '308 CC',36");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '408',36");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '508',36");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Boxer',36");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Hoggar',36");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Partner',36");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'RCZ',36");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '911',37");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Boxster',37");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Boxster S',37");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cayenne',37");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cayman',37");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Cayman S',37");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Macan',37");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Panamera',37");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT '2500',38");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Clio',39");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Duster',39");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Fluence',39");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Grand Tour',39");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Kangoo Express',39");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Logan',39");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Master',39");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Sandero',39");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Sandero Stepway',39");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Symbol',39");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Fortwo MHD ',40");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Fortwo Passion Cabrio',40");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Fortwo Passion Coupé ',40");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Actyon Sports',41");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Korando',41");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Kyron',41");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Forester',42");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Impreza Hatch',42");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Impreza Sed?',42");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Legacy',42");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Outback',42");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Tribeca',42");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Grand Vitara',43");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Jimny',43");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'SX4',43");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Camry',44");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Corolla',44");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Etios Hatch',44");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Etios Sedã',44");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Hilux',44");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Prius',44");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'RAV4',44");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'SW4',44");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'T4 ',45");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Amarok',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Crossfox',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Fox',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Fusca',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Gol',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Gol G4',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Golf',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Jetta ',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Jetta Variant',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Kombi',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Parati',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Passat',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Passat Variant',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Polo',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Polo Sedan',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Saveiro',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Space Cross',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'SpaceFox',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Tiguan',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Touareg',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Up!',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'Voyage',46");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'C30',47");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'S60',47");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'V40',47");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'XC60 ',47");
        db.execSQL("INSERT INTO modelo (nome, idMarca) SELECT 'XC90',47");

    }
}
